name: Build & Pack Check

on:
  push:
    branches: [ main, V*, develop ]
  pull_request:
    branches: '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    

    # Restore Nuget Package From Dev-Sufiyan Packages
    # - name: Configure NuGet to use GitHub Packages
    #   run: |
    #       dotnet nuget add source https://nuget.pkg.github.com/Dev-Sufiyan/index.json \
    #       --name github \
    #       --username Dev-Sufiyan \
    #       --password ${{ secrets.PACKAGES_READ_TOKEN }} \
    #       --store-password-in-clear-text

    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build for Test
      run: dotnet build --configuration Debug
    
    - name: Test
      run: dotnet test ./Genesis.Package.Template.Test/Genesis.Package.Template.Test.csproj --no-build --verbosity normal

    - name: Build for Pack
      run: dotnet build --configuration Release --no-restore
      
    - name: NuGet Pack Check
      run: dotnet pack Genesis.Package.Template/Genesis.Package.Template.csproj --configuration Release /p:PackageVersion=0.0.0-PRCheck --output ./artifacts
